[package]
name = "next-intl-extractor"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
next-intl-shared = { path = "../shared" }
napi.workspace = true
napi-derive.workspace = true
swc_core.workspace = true
tokio = { version = "1", features = ["fs", "rt"] }
rayon = "1.10"
futures = "0.3"
walkdir = "2"

[build-dependencies]
napi-build = "2.0"
