[package]
name = "next-intl-extracted-swc-plugin"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
next-intl-shared = { path = "../shared" }
swc_core.workspace = true
swc_ecma_ast.workspace = true
swc_ecma_visit.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
