name: Feature request
description: Suggest an idea for this project
labels:
  - enhancement
  - unconfirmed
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to improve next-intl!
  - type: markdown
    attributes:
      value: |
        Please keep in mind:

        - If you're looking for specific support with your project, you can consider [asking for community support](https://github.com/amannn/next-intl/issues/new/choose) instead.
        - If something doesn't work as expected, you might want to [create a bug report](https://github.com/amannn/next-intl/issues/new/choose) instead.
        - Please double check the [docs](https://next-intl.dev) to see if your feature request is already supported.
        - Please also check the [existing issues](https://github.com/amannn/next-intl/issues) to see if your feature request was already discussed.

        If you have a feature request that has not been discussed yet, please fill out this form completely.
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. E.g. I'm always frustrated when …
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true
