name: Bug report
description: Create a bug report
labels:
 - bug
 - unconfirmed
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to file a bug report!
  - type: markdown
    attributes:
      value: |
        **Creating a good bug report takes time.**
        
        To help us resolve the issue quickly, please simplify the reproduction as much as possible by removing any unnecessary code, files, and dependencies that are not directly related to the problem. The easier it is for us to see the issue, the faster we can help you.

        **Please note:**
        1. Bug reports without a reproduction may be closed immediately.
        2. General usage questions are not bug reports. Please [submit usage questions on Stack Overflow](https://stackoverflow.com/questions/ask) instead.
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: input
    attributes:
      label: Mandatory reproduction URL (CodeSandbox or GitHub repository)
      description: |
        **Templates:**
        - [CodeSandbox (`app` directory)](https://codesandbox.io/p/sandbox/next-intl-bug-template-forked-yow8ep),
        - [CodeSandbox (`pages` directory)](https://codesandbox.io/p/sandbox/next-intl-bug-template-pages-krm37f)
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction description
      description: Describe how the issue can be reproduced based on your provided CodeSandbox or GitHub repository.
      value: |
        Steps to reproduce:
        1. Open reproduction
        2. Click on …
        3. See error: … 
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behaviour
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
