import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { PlaygroundSidebar } from "./_components/playground-sidebar";
import PlaygroundByline from "./_components/playground-byline";
import { ClientProviders } from "./_components/client-providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`font-sans ${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClientProviders>
          <PlaygroundSidebar />
          <div className="lg:pl-72">
            <div className="mx-auto mt-12 mb-24 max-w-4xl -space-y-[1px] lg:px-8 lg:py-8">
              {children}
              <PlaygroundByline />
            </div>
          </div>
        </ClientProviders>
      </body>
    </html>
  );
}

