name: Add comment
on:
  issues:
    types:
      - labeled
jobs:
  reproduction-missing:
    if: github.event.label.name == 'reproduction-missing'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thank you for your report!
            
            Unfortunately, the reproduction is missing or incomplete, and as such we cannot investigate this issue. Please add a reproduction to the issue, otherwise it will be closed automatically.

            **Templates:**
             - [App Router](https://github.com/amannn/next-intl-bug-repro-app-router)
             - [Pages Router](https://github.com/amannn/next-intl/tree/main/examples/example-pages-router)
            
            **Creating a good bug report takes time.**
            
            To help us resolve the issue quickly, please simplify the reproduction as much as possible by removing any unnecessary code, files, and dependencies that are not directly related to the problem. The easier it is for us to see the issue, the faster we can help you.

            Apart from the reproduction, make sure to include the precise steps on how to reproduce the issue, e.g.:

            1. Open reproduction
            2. Click on …
            3. See error: … 

            Thank you for your understanding!

            <details>
              <summary>FAQ</summary>

              **"I've included a reproduction, what is missing?"**

              This comment might have been added because your reproduction doesn't point to a destination where the issue can be reproduced. Please make sure that the latest changes were saved in the reproduction and that the link is correct.
            </details>

  needs-isolation:
    if: github.event.label.name == 'needs-isolation'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thank you for your report!
            
            From the currently available context in this issue, it's unclear wether the erroneous behavior is caused by Next.js, `next-intl` or a 3rd party library that you're using. Please isolate the issue further to be sure that the issue is _caused_ by `next-intl`. When in doubt, please search on [the Next.js issue tracker](https://github.com/vercel/next.js/issues) or related resources of 3rd party libraries you might be using.

            If you're able to isolate the issue to `next-intl`, please provide a minimal reproduction that ideally doesn't involve any 3rd party libraries or alternatively demonstrates that `next-intl` is causing the issue.

            Thank you for your understanding!
